export type StockInfo = {
  name: string
  kind: 'Stock' | 'ETF' | 'Commodity ETF' | 'Pre-IPO' | 'Preferred'
  exchange: string
  sector: string
  summary: string
}

/**
 * Static reference data for the underlying assets StockPass tracks.
 * Descriptive only — what the company does, where it trades.
 * No prices, no valuations, nothing that goes stale within a quarter.
 */
export const STOCKS: Record<string, StockInfo> = {
  AAPL: {
    name: 'Apple Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Consumer Technology',
    summary: 'Designs and sells the iPhone, Mac and Apple Watch, plus a growing services business built around them.',
  },
  ABBV: {
    name: 'AbbVie Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Pharmaceuticals',
    summary: 'Research-based pharmaceutical company focused on immunology, oncology and neuroscience treatments.',
  },
  ADBE: {
    name: 'Adobe Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Software',
    summary: 'Creative and document software sold by subscription, including Photoshop, Premiere and Acrobat.',
  },
  AMD: {
    name: 'Advanced Micro Devices',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Semiconductors',
    summary:
      'Designs processors and graphics chips for PCs, servers and data centres, competing with Intel and Nvidia.',
  },
  AMZN: {
    name: 'Amazon.com Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'E-commerce & Cloud',
    summary: 'Online retail at global scale, plus Amazon Web Services, the largest cloud infrastructure provider.',
  },
  AVGO: {
    name: 'Broadcom Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Semiconductors',
    summary: 'Supplies networking, broadband and wireless chips, and enterprise infrastructure software.',
  },
  CAT: {
    name: 'Caterpillar Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Industrial Machinery',
    summary: 'Builds construction and mining equipment, diesel engines and industrial turbines worldwide.',
  },
  COIN: {
    name: 'Coinbase Global',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Crypto Exchange',
    summary: 'Operates the largest regulated crypto exchange in the United States, for retail and institutions.',
  },
  CRCL: {
    name: 'Circle Internet Group',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Stablecoin Infrastructure',
    summary: 'Issues USDC, the dollar stablecoin used to price and settle most trades in this app.',
  },
  CRM: {
    name: 'Salesforce Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Enterprise Software',
    summary: 'Customer relationship management software delivered as a cloud subscription to enterprises.',
  },
  CSCO: {
    name: 'Cisco Systems',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Networking Hardware',
    summary: 'Supplies routers, switches and security products that carry a large share of internet traffic.',
  },
  CVX: {
    name: 'Chevron Corporation',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Energy',
    summary: 'Integrated oil and gas company covering exploration, refining and distribution.',
  },
  DIS: {
    name: 'The Walt Disney Company',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Media & Entertainment',
    summary: 'Film and television studios, theme parks, and the Disney+ streaming service.',
  },
  GLD: {
    name: 'SPDR Gold Shares',
    kind: 'Commodity ETF',
    exchange: 'NYSE Arca',
    sector: 'Precious Metals',
    summary: 'Holds physical gold bullion in vaults; each share represents a fraction of an ounce.',
  },
  GME: {
    name: 'GameStop Corp.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Specialty Retail',
    summary: 'Video game and collectibles retailer, known for the 2021 short squeeze and a heavy retail following.',
  },
  GOOGL: {
    name: 'Alphabet Inc. (Class A)',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Internet & Advertising',
    summary: 'Parent of Google Search, YouTube, Android and Google Cloud; revenue is mostly advertising.',
  },
  GS: {
    name: 'Goldman Sachs Group',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Investment Banking',
    summary: 'Investment bank active in trading, advisory, asset management and wealth management.',
  },
  HIMS: {
    name: 'Hims & Hers Health',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Telehealth',
    summary: 'Direct-to-consumer telehealth platform selling treatments by subscription in the US.',
  },
  HOOD: {
    name: 'Robinhood Markets',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Retail Brokerage',
    summary: 'Commission-free brokerage app for stocks, options and crypto, aimed at retail investors.',
  },
  INTC: {
    name: 'Intel Corporation',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Semiconductors',
    summary: 'Designs and manufactures processors; one of the few chip firms that still owns its fabs.',
  },
  IONQ: {
    name: 'IonQ Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Quantum Computing',
    summary: 'Builds trapped-ion quantum computers and sells access to them through cloud providers.',
  },
  JNJ: {
    name: 'Johnson & Johnson',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Pharmaceuticals',
    summary: 'Pharmaceutical and medical device company, one of the longest-standing dividend payers in the index.',
  },
  JPM: {
    name: 'JPMorgan Chase',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Banking',
    summary: 'The largest US bank by assets, spanning consumer banking, investment banking and asset management.',
  },
  KO: {
    name: 'The Coca-Cola Company',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Beverages',
    summary: 'Sells non-alcoholic beverage concentrates and syrups to bottlers in over 200 markets.',
  },
  LLY: {
    name: 'Eli Lilly and Company',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Pharmaceuticals',
    summary: 'Pharmaceutical company known for diabetes and obesity treatments, plus oncology and neuroscience.',
  },
  MCD: {
    name: "McDonald's Corporation",
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Restaurants',
    summary:
      'Operates and franchises fast-food restaurants worldwide; most revenue comes from franchising and property.',
  },
  META: {
    name: 'Meta Platforms',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Social Media',
    summary: 'Runs Facebook, Instagram and WhatsApp, funded by advertising, with heavy spending on AI infrastructure.',
  },
  MRK: {
    name: 'Merck & Co.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Pharmaceuticals',
    summary: 'Develops prescription medicines and vaccines, with a large oncology franchise.',
  },
  MSFT: {
    name: 'Microsoft Corporation',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Software & Cloud',
    summary: 'Windows, Office and Azure cloud services, plus a deep investment in AI infrastructure.',
  },
  MSTR: {
    name: 'Strategy (MicroStrategy)',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Bitcoin Treasury',
    summary: 'Business intelligence software firm that holds a very large corporate bitcoin treasury.',
  },
  NFLX: {
    name: 'Netflix Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Streaming Media',
    summary: 'Subscription streaming service producing and licensing film and television worldwide.',
  },
  NKE: {
    name: 'NIKE Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Apparel & Footwear',
    summary: 'Designs and markets athletic footwear and apparel, sold through retail and direct channels.',
  },
  NVDA: {
    name: 'NVIDIA Corporation',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Semiconductors',
    summary: 'Designs the GPUs and data-centre accelerators that most AI training runs on.',
  },
  OKLO: {
    name: 'Oklo Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Nuclear Energy',
    summary: 'Developing small modular fission reactors to sell power under long-term contracts.',
  },
  ORCL: {
    name: 'Oracle Corporation',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Enterprise Software',
    summary: 'Database and enterprise application software, expanding into cloud infrastructure for AI workloads.',
  },
  PEP: {
    name: 'PepsiCo Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Food & Beverages',
    summary: 'Beverages and snack foods, including Pepsi, Gatorade, Lay\u2019s and Quaker.',
  },
  PFE: {
    name: 'Pfizer Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Pharmaceuticals',
    summary: 'Develops and manufactures prescription medicines and vaccines across several therapy areas.',
  },
  PLTR: {
    name: 'Palantir Technologies',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Data Analytics',
    summary: 'Builds data integration and analysis platforms for governments, defence and large enterprises.',
  },
  PYPL: {
    name: 'PayPal Holdings',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Payments',
    summary: 'Digital payments platform covering PayPal, Venmo and merchant checkout services.',
  },
  QCOM: {
    name: 'QUALCOMM Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Semiconductors',
    summary: 'Designs mobile chipsets and licenses the wireless patents behind much of modern cellular.',
  },
  QQQ: {
    name: 'Invesco QQQ Trust',
    kind: 'ETF',
    exchange: 'NASDAQ',
    sector: 'Index Fund',
    summary: 'Tracks the Nasdaq-100: the largest non-financial companies listed on the Nasdaq.',
  },
  RKLB: {
    name: 'Rocket Lab',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Aerospace',
    summary: 'Launches small satellites on its Electron rocket and builds spacecraft components.',
  },
  SBUX: {
    name: 'Starbucks Corporation',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Restaurants',
    summary: 'Operates and licenses coffeehouses worldwide, with a large mobile ordering and loyalty business.',
  },
  SMCI: {
    name: 'Super Micro Computer',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Server Hardware',
    summary: 'Builds high-performance servers and storage systems, heavily exposed to AI data-centre demand.',
  },
  SOFI: {
    name: 'SoFi Technologies',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Digital Banking',
    summary: 'Online personal finance company offering lending, banking and investing in one app.',
  },
  SPCX: {
    name: 'SpaceX (pre-IPO exposure)',
    kind: 'Pre-IPO',
    exchange: 'Private',
    sector: 'Aerospace',
    summary:
      'SpaceX is privately held and not listed on a public exchange. Exposure here is structured by the issuer, so read their terms carefully before treating it like a listed share.',
  },
  SPY: {
    name: 'SPDR S&P 500 ETF Trust',
    kind: 'ETF',
    exchange: 'NYSE Arca',
    sector: 'Index Fund',
    summary: 'Tracks the S&P 500: the 500 largest US public companies, weighted by market value.',
  },
  STRC: {
    name: 'Strategy preferred shares',
    kind: 'Preferred',
    exchange: 'NASDAQ',
    sector: 'Bitcoin Treasury',
    summary:
      'A preferred share class issued by Strategy. Preferred shares rank ahead of common stock and behave differently; check the issuer\u2019s terms.',
  },
  TSLA: {
    name: 'Tesla Inc.',
    kind: 'Stock',
    exchange: 'NASDAQ',
    sector: 'Electric Vehicles',
    summary: 'Builds electric vehicles, battery storage and solar products, with work on autonomy and robotics.',
  },
  TSM: {
    name: 'Taiwan Semiconductor (ADR)',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Semiconductors',
    summary: 'The world\u2019s largest contract chip manufacturer; fabricates for Apple, Nvidia and AMD.',
  },
  UBER: {
    name: 'Uber Technologies',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Mobility & Delivery',
    summary: 'Operates ride-hailing, food delivery and freight marketplaces across dozens of countries.',
  },
  V: {
    name: 'Visa Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Payments',
    summary: 'Runs the card payment network that routes transactions between banks and merchants.',
  },
  VZ: {
    name: 'Verizon Communications',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Telecommunications',
    summary: 'US wireless and broadband carrier, one of the higher dividend payers in the index.',
  },
  WMT: {
    name: 'Walmart Inc.',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Retail',
    summary: 'The largest retailer in the world by revenue, with a fast-growing e-commerce arm.',
  },
  XOM: {
    name: 'Exxon Mobil Corporation',
    kind: 'Stock',
    exchange: 'NYSE',
    sector: 'Energy',
    summary: 'Integrated oil and gas major covering exploration, refining and chemicals.',
  },
}

export function stockInfo(ticker: string): StockInfo | null {
  return STOCKS[ticker.toUpperCase()] ?? null
}
